### ISSUE TITLE
Extension of the configuration options possible

### ISSUE THREAD

**Issue by banane-m** [KastB/addon-fhem#2]
Hello, 
could the configuration (addon homeassitant)  be extended so that Maplecul usb sticks or others could be connected and the telnet port could be forwarded to the outside.

thank you very much

**Comment by KastB** [comment]
There are two separate topics here:
1) Maplecul probably requires tty to be forwarded - this option should already be set (  "uart": true) and it works for my cul (I dont know if the maplecul requires s.th. different?)
2) the forwarded telnet port: Can you give me an example of an addon that already does this? So that I can get an idea of what this is good for and how this can be achieved. When I needed a shell in the container I simply did "docker exec -it addon_XXX /bin/bash".

**Comment by banane-m** [comment]
It would be nice in the config selection menu similar to the "deCONZ addon", with selection of USB and network port for mapping, where you could, for example, pass on the telnet port

**Comment by KastB** [comment]
I'm not sure how to achieve this, but feel free to send a merge request.

**Comment by KastB** [comment]
There was a pull request from ZwergNase which hopefully solved the telnet issue.
Not sure if there is an issue with maplecul as I thought it would be fine with "uart": true
If there would be no further info I would close this issue in a few days.
